import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useState } from 'react'
// import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [result, setResult] = useState<any>()
  const [error, setError] = useState<any>()
  // console.log(window.PaymentRequest)

  function onBuyClicked() {
    if (!window.PaymentRequest) {
      console.log('Web payments are not supported in this browser.1');
      return;
    }
  
    // Create supported payment method.
    const supportedInstruments:PaymentMethodData[] = [
      {
        supportedMethods: 'upi://pay',
        data: {
          pa: 'prakhart4@okicici',
          pn: 'Prakhar',
          tr: '1234ABCD',  // Your custom transaction reference ID
          url: 'http://localhost:3000/',
          mc: '5411', //Your merchant category code
          tn: 'Purchase in Merchant',
        },
      }
    ];
  
    // Create order detail data.
    const details = {
      total: {
        label: 'Total',
        amount: {
          currency: 'INR',
          value: '10.01', // sample amount
        },
      },
      displayItems: [{
        label: 'Original Amount',
        amount: {
          currency: 'INR',
          value: '10.01',
        },
      }],
    };
    // console.log('hi');
  
    // Create payment request object.
    let request:any = null;
    try {
      request = new PaymentRequest(supportedInstruments, details);
    } catch (e:any) {
      console.log('Payment Request Error: ' + e.message);
      return;
    }
    console.log(request);
    
    if (!request) {
      console.log('Web payments are not supported in this browser.');
      return;
    }
  
    var canMakePaymentPromise = request.canMakePayment(request);
    canMakePaymentPromise
        .then((result:any )=> {          
          request?.show(request, result);
        })
        .catch((err:any) => {
          request?.show(request);
          console.log('Error calling checkCanMakePayment: ' + err);
        });
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <h6>{JSON.stringify(result)}</h6>
        <input type='button' onClick={onBuyClicked} value='pay the upi' />
        <a type='button' href='upi://pay?pn=the%20business&pa=prakhartomar@icici&cu=INR&am=0.0' >pay the using upi</a>
        <h6>{JSON.stringify(error)}</h6>
      </main>
    </>
  )
}
