import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useState } from 'react'
// import axios from 'axios';
// import styles from '@/styles/Home.module.css'

const myParams= {
  pa: 'prakhart4@okicici',
  pn: 'Prakhar',
  tr: '1234ABCD',  // Your custom transaction reference ID
  url: "http://192.168.1.4/api/callback",
  mc: '5411', //Your merchant category code
  tn: "bill",
  am: "10.00"
}

export default function Home() {
  const [result, setResult] = useState<any>()
  const [error, setError] = useState<any>()
  // console.log(window.PaymentRequest)

  function onBuyClicked() {
    window.location.href = "upi://pay?pa=prakhartomar@upi&pn=Merchant%20Name&tr=1234567890&am=1.00&mc=1234&tn=Transaction%20Note&refUrl=http://192.168.1.4:3000/Success";
    
    if (!window.PaymentRequest) {
      console.log('Web payments are not supported in this browser.1');
      return;
    }
  
    // Create supported payment method.
    const supportedInstruments:PaymentMethodData[] = [
      {
        supportedMethods: 'upi://pay',
        data: {
          pa: 'prakhart4@okicici',
          pn: 'Prakhar',
          tr: '1234ABCD',  // Your custom transaction reference ID
          url: process.cwd()+"/api/callback",
          mc: '5411', //Your merchant category code
          tn: 'Purchase in Merchant',
        },
      }
    ];
  
    // Create order detail data.
    const details = {
      total: {
        label: 'Total',
        amount: {
          currency: 'INR',
          value: '10.01', // sample amount
        },
      },
      displayItems: [{
        label: 'Original Amount',
        amount: {
          currency: 'INR',
          value: '10.01',
        },
      }],
    };
    // console.log('hi');
  
    // Create payment request object.
    let request:any = null;
    try {
      request = new PaymentRequest(supportedInstruments, details);
    } catch (e:any) {
      console.log('Payment Request Error: ' + e.message);
      return;
    }
    console.log(request);
    
    if (!request) {
      console.log('Web payments are not supported in this browser.');
      return;
    }
  
    var canMakePaymentPromise = request.canMakePayment(request);
    canMakePaymentPromise
        .then((result:any )=> {          
          request?.show(request, result);
        })
        .catch((err:any) => {
          request?.show(request);
          console.log('Error calling checkCanMakePayment: ' + err);
        });
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <h6>{JSON.stringify(result)}</h6>
        <input type='button' onClick={onBuyClicked} value='pay the with upi' />
        <a type='button' href={
          "upi://pay?pa=prakhartomar@upi&pn=Merchant%20Name&tr=1234567890&am=1.00&mc=1234&tn=Transaction%20Note&refUrl=http://192.168.1.4:3000/Success"
          // 'upi://pay?'+new URLSearchParams(myParams).toString()
          } >pay the with upi</a>
        <h6>{JSON.stringify(error)}</h6>
      </main>
    </>
  )
}
